name: ci_build

on:
  push:
    branch:
      - 'main'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: 'true'
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade --disable-pip-version-check pip
          python -m pip install .[all]
      - name: Install latest pip, build, twine
        run: |
          python -m pip install --upgrade --disable-pip-version-check pip
          python -m pip install --upgrade build twine
      - name: Run tests
        run: |
          pytest
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist/*
